{
	"points" : [
		{ "country": "Portugal" , "data": "117"},
		{ "country": "Macedonia" , "data": "81"},
		{ "country": "Slovakia" , "data": "111"},
		{ "country": "Iceland" , "data": "3"},
		{ "country": "Romania" , "data": "91"},
		{ "country": "Poland" , "data": "123"},
		{ "country": "Denmark" , "data": "129"},
		{ "country": "Luxembourg" , "data": "201"},
		{ "country": "Serbia" , "data": "93"},
		{ "country": "Greece" , "data": "82"},
		{ "country": "Turkey" , "data": "104"},
		{ "country": "Czech Republic" , "data": "135"},
		{ "country": "Liechtenstein" , "data": "233"},
		{ "country": "Norway" , "data": "16"},
		{ "country": "Austria" , "data": "98"},
		{ "country": "Spain" , "data": "94"},
		{ "country": "Bulgaria" , "data": "62"},
		{ "country": "France" , "data": "103"},
		{ "country": "Croatia" , "data": "79"},
		{ "country": "Slovenia" , "data": "98"},
		{ "country": "Ireland" , "data": "69"},
		{ "country": "Albania" , "data": "105"},
		{ "country": "Switzerland" , "data": "195"},
		{ "country": "Belarus" , "data": "46"},
		{ "country": "Malta" , "data": "1,306"},
		{ "country": "Bosnia and Herzegovina" , "data": "76"},
		{ "country": "Ukraine" , "data": "73"},
		{ "country": "Italy" , "data": "205"},
		{ "country": "Montenegro" , "data": "47"},
		{ "country": "Moldova" , "data": "106"},
		{ "country": "Lithuania" , "data": "54"},
		{ "country": "Netherlands" , "data": "406"},
		{ "country": "Holy See (Vatican City)" , "data": "1,914"},
		{ "country": "Sweden" , "data": "22"},
		{ "country": "Monaco" , "data": "15,254"},
		{ "country": "United Kingdom" , "data": "262"},
		{ "country": "Finland" , "data": "16"},
		{ "country": "Andorra" , "data": "183"},
		{ "country": "Germany" , "data": "227"},
		{ "country": "Hungary" , "data": "107"},
		{ "country": "Latvia" , "data": "34"},
		{ "country": "Belgium" , "data": "342"},
		{ "country": "Estonia" , "data": "28"},
		{ "country": "San Marino" , "data": "537"}
	]
}